# Enables broadcasting
enable-broadcast: true

# In what servers do NOT send a message?
disabled-servers:
#- testServer

# The file that will contain the messages to broadcast.
# Supports custom file types, such as .yml or .txt
message-file: "messages.txt"

# The minimal amount of players that has to be online for a message to broadcast.
# Set 0 to disable this feature.
min-players: 1

# Placeholder formats
placeholder-format:
  time:
    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    time-zone: "GMT0"

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Used for %server-time% placeholder.
    time-format:
      format: "mm:HH"
    # Used for %date% placeholder.
    date-format:
      format: "dd/MM/yyyy"

    # %title% placeholder to show the title in a message.
    title: "&c[&aAuto&9Messager&c] "

    # %suffix% placeholder to show the suffix in a message.
    suffix: ""

# Time interval for sending messages.
time: 3

# Time settings
# Variables: seconds, days, minutes, hours, milliseconds
time-setup: minutes

# Want to broadcast the messages in ordered or randomly?
# Minimum 2 message needed to get a random message!
random: false

# Does the plugin send the sent auto-messages to console?
broadcast-to-console: false

# Plugin messages
messages:
  reload-config: "&aThe plugin successfully reloaded!"
  no-permission: "&cYou don't have permission for this!"
  no-message-to-list: "&cThere is no message in the file."
  broadcast-message: "&a[&cBroadcast&a]&r %message%"
  broadcast-usage: "&cUsage:&7 '/automessager bc <message>'"
  toggle:
    enabled: "&aThe messages successfully turned on!"
    disabled: "&cThe messages successfully turned off!"
    no-player: "&cThere is no player available on the server."
  chat-messages:
  - "&8&l-----------"
  - "&7/&aautomessager reload&7 (or rl)&e -&6 Reloads the plugin and config."
  - "&7/&aautomessager toggle&e -&6 Toggle auto message."
  - "&7/&aautomessager list&5 -&6 List messages."
  - "&7/&aautomessager broadcast&5 -&6 Broadcasting a message."
  - "&8&l-----------"

# DO NOT CHANGE THIS!
config-version: 2
