#=================================OOO====================================#
#                   AutoMessager Configuration File                      #
#=================================OOO====================================#
# config.yml file. Plugin version: 1.5                                   #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configurations]                                               #
# https://github.com/montlikadani/AutoMessager/blob/master/config.yml    #
#                                                                        #
# [Placeholders]                                                         #
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/             #
#                                                                        #
# [Other placeholders]                                                   #
# https://github.com/montlikadani/AutoMessager/wiki/placeholders         #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - In case of an error, write here:                                     #
# https://github.com/montlikadani/AutoMessager/issues                    #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/AutoMessager/wiki/Symbols              #
#=================================OOO====================================#

# If these number mark (#) are in the way, you can safely remove it.

#=========================================#
#         AutoMessage Settings            #
#=========================================#
# Enables broadcasting.
enable-broadcast: true

# Enable to use PlaceholderAPI for the plugin.
placeholderapi: false

# In what worlds do NOT send a message?
# If you do not want one, use it like this: disabled-worlds: []
disabled-worlds: []

# The messages.txt (you have entered here) can use special characters here:
# https://github.com/montlikadani/AutoMessager/wiki/Symbols
# The file that will contain the messages to broadcast.
message-file: 'messages.txt'

# The minimal amount of players that has to be online for a message to broadcast.
# Set to 0 to disable this feature.
min-players: 1

# The %title% placeholder. You can enter this in the messages.txt file.
# Use %newline% placeholder.
title: '&c[&aAuto&9Messager&c] '

# Time is the time between each message.
time: 3
# Time settings.
# Variables: ticks, sec, min, h
# Example: 20 ticks = 1 second; 1 second = 20 ticks; 1 minute = 60 second; 1 hour = 60 minute
time-setup: min

# Want to broadcast the messages in order or randomly?
random: false

# Broadcast to console.
# WARNING! It does not show placeholders and symbols in the console.
broadcast-to-console: false

# Run commands after sending auto messages.
run-commands:
  # Player commands.
  player:
    enable: false
    # Use %player%, %player-displayname%, %world% placeholder.
    commands:
    - '/baltop'
  # Console commands.
  console:
    enable: false
    # Use %player%, %player-displayname%, %world% placeholder.
    commands:
    - '/kit tools %player%'
    - '/bal %player%'

# Sound playback when broadcasting.
# All sounds:
# 1.9.x, 1.10.x, 1.11.x, 1.12.x: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# 1.8.x: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
# 1.7.x: https://jd.bukkit.org/org/bukkit/Sound.html
sound:
  enable: false
  # Example: 1.9.x: ENTITY_EXPERIENCE_ORB_PICKUP; 1.8: ORB_PICKUP
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 10
  pitch: 1

#=========================================#
#             Plugin Settings             #
#=========================================#
# The AutoMessager plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable-message: true
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v1.5&a!'
plugin-disable-message: true
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: automessager.plugininfo
default-can-see-plugin-information: false

# Unknown-command - If more than one word/letter you write to it.
# Example: /am reload something...
# Use %command%, %prefix% placeholder.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
# >> NO supported the PlaceholderAPI! <<
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'
