# Enables broadcasting messages
enable-broadcast: true

# Enable to use PlaceholderAPI for the plugin.
placeholderapi: true

# Save the toggled messages to a file to load after server restart.
remember-toggle-to-file: true

# Used for the /am list command.
show-max-row-in-one-page: 4

# In what worlds do NOT send a message?
disabled-worlds:
#- hubs

# The file that will contain the messages to broadcast.
# Supports custom file types, such as .yml or .txt
message-file: "announces.yml"

# The minimal amount of players that has to be online for a message to broadcast.
# Set to 0 to disable this feature.
min-players: 1

# Disable sending auto-messages when the player afk?
# Requires Essentials or CMI plugin
disable-messages-when-player-afk: false

# Custom variables that will be replaced in the custom message file.
# This useful when we are creating a lot of lines with the same name.
# Usage: <nameOfPlaceholder>: "&6Text..."
custom-variables:
  <title>: "&c[&aAuto&9Messager&c] "
  <prefix>: "&5&m======================"
  <suffix>: "&asuffix"

# Placeholder formats
placeholder-format:
  # Time settings
  time:
    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    time-zone: "GMT0"

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Used for %server-time% placeholder.
    time-format:
      format: "mm:HH"
    # Used for %date% placeholder.
    date-format:
      format: "dd/MM/yyyy"

# Time interval for sending messages.
time: 3

# Time settings
# Variables: ticks, second, minute, hour, custom, given
# Example: 20 ticks = 1 second; 1 second = 20 ticks; 1 minute = 60 second; 1 hour = 60 minute
# custom usage: "00:01:00" - this counts 1 minute and after it's taken then sending the message
# given usage: "12:50:00" - this will send a message at 12:50 with your current time zone
time-setup: min

# Want to broadcast the messages in ordered or randomly?
# Minimum 2 message needed to get a random message!
random: false

# Does the plugin send the sent auto-messages to console?
broadcast-to-console: false

# Run commands after sending auto messages.
run-commands:
  # Usage: <commandSender>: <any command>
  commands:
  #- "player: baltop"
  #- "console: kit tools %player%"

# Sound playback when broadcasting.
# All sounds:
# 1.9+: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# 1.8.x: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
sound:
  # Example: 1.9+: ENTITY_EXPERIENCE_ORB_PICKUP; 1.8: ORB_PICKUP
  # Usage: SOUND_NAME, volume, pitch
  #type: ENTITY_EXPERIENCE_ORB_PICKUP, 10, 1

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Download releases to releases folder
# This only works if the "check-update" is true.
download-updates: false

# Log plugin messages into console.
logconsole: true

# DO NOT CHANGE THIS!
config-version: 6
