# Enables broadcasting.
enable-broadcast: true

# Enable to use PlaceholderAPI for the plugin.
placeholderapi: false

# Use JSON message in file?
# Usage: https://github.com/montlikadani/AutoMessager/wiki/File-usage#json-message
use-json-message: false

# Used for the /am list command.
show-max-row-in-one-page: 8

# In what worlds do NOT send a message?
disabled-worlds:
#- hubs

# The file that will contain the messages to broadcast.
# Supports custom file types, such as .yml or .txt
message-file: "messages.txt"

# The minimal amount of players that has to be online for a message to broadcast.
# Set to 0 to disable this feature.
min-players: 1

# Disable sending auto-messages when the player afk?
# Required Essentials plugin!
disable-messages-when-player-afk: false

# Placeholder formats
placeholder-format:
  # %title% placeholder to show the title in a message.
  title: "&c[&aAuto&9Messager&c] "

  # %suffix% placeholder to show the suffix in a message.
  suffix: ""

  # Time settings
  time:
    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    time-zone: "GMT0"

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Used for %server-time% placeholder.
    time-format:
      format: "mm:HH"
    # Used for %date% placeholder.
    date-format:
      format: "dd/MM/yyyy"

# Time interval for sending messages.
time: 3

# Time settings
# Variables: ticks, second (or sec), minute (or min), hour (or h)
# Example: 20 ticks = 1 second; 1 second = 20 ticks; 1 minute = 60 second; 1 hour = 60 minute
time-setup: min

# Want to broadcast the messages in ordered or randomly?
# Minimum 2 message needed to get a random message!
random: false

# Does the plugin send the sent auto-messages to console?
broadcast-to-console: false

# Run commands after sending auto messages.
run-commands:
  # Usage: <commandSender>: <any command>
  commands:
  #- "player: baltop"
  #- "console: kit tools %player%"

# Sound playback when broadcasting.
# All sounds:
# 1.9+: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# 1.8.x: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
sound:
  enable: false

  # Example: 1.9+: ENTITY_EXPERIENCE_ORB_PICKUP; 1.8: ORB_PICKUP
  # Usage: SOUND_NAME, volume, pitch
  type: ENTITY_EXPERIENCE_ORB_PICKUP, 10, 1

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Plugin enable/disable messages in console.
# Use %newline% placeholder.
plugin-enable: '&6[&4Auto&9Messager&6]&7 >&a The plugin successfully enabled&6 v${version}&a!'
plugin-disable: '&6[&4Auto&9Messager&6]&7 >&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 5
