#=================================OOO====================================#
#                   AutoMessager Configuration File                      #
#=================================OOO====================================#
# config.yml file. Plugin version: ${version}                            #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configuration]                                                #
# https://github.com/montlikadani/AutoMessager/blob/master/config.yml    #
#                                                                        #
# [Placeholders]                                                         #
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/             #
#                                                                        #
# [Other placeholders]                                                   #
# https://github.com/montlikadani/AutoMessager/wiki/placeholders         #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# # - If you find a bug, send here:                                      #
# https://github.com/montlikadani/AutoMessager/issues                    #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/AutoMessager/wiki/Symbols              #
# - If the string is empty does not send the message.                    #
#=================================OOO====================================#

#=========================================#
#         AutoMessage Settings            #
#=========================================#
# Enables broadcasting.
enable-broadcast: true

# Enable to use PlaceholderAPI for the plugin.
placeholderapi: false

# Use JSON message in file?
# Usage: https://github.com/montlikadani/AutoMessager/wiki/File-usage#json-message
use-json-message: false

# In what worlds do NOT send a message?
disabled-worlds: []

# The messages.txt (you have entered here) can use special characters here:
# https://github.com/montlikadani/AutoMessager/wiki/Symbols
# The file that will contain the messages to broadcast.
message-file: 'messages.txt'

# The minimal amount of players that has to be online for a message to broadcast.
# Set to 0 to disable this feature.
min-players: 1

# Disable sending auto-messages when the player afk?
# Required Essentials plugin!
disable-messages-when-player-afk: false

# The %title% placeholder. You can enter this in the file.
# Use %newline% placeholder.
title: '&c[&aAuto&9Messager&c] '

# The suffix of the sender. You can enter this in the file.
# Use %suffix% placeholder in the file.
suffix: ''

# Time is the time between each message.
time: 3
# Time settings.
# Variables: ticks, sec, second, min, minute h, hour
# Example: 20 ticks = 1 second; 1 second = 20 ticks; 1 minute = 60 second; 1 hour = 60 minute
time-setup: min

# Want to broadcast the messages in order or randomly?
# Minimum 2 message needed!
random: false

# Broadcast to console.
# WARNING! It does not show symbols and JSON message in the console.
broadcast-to-console: false

# Run commands after sending auto messages.
run-commands:
  # Player commands.
  player:
    enable: false
    # Use %player%, %player-displayname%, %world% placeholder.
    commands:
    - 'baltop'
  # Console commands.
  console:
    enable: false
    # Use %player%, %player-displayname%, %world% placeholder.
    commands:
    - 'kit tools %player%'
    - 'bal %player%'

# Sound playback when broadcasting.
# All sounds:
# 1.9.x-1.13.x: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# 1.8.x: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
# 1.7.x: https://jd.bukkit.org/org/bukkit/Sound.html
sound:
  enable: false
  # Example: 1.9.x: ENTITY_EXPERIENCE_ORB_PICKUP; 1.8: ORB_PICKUP
  type: ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 10
  pitch: 1

#=========================================#
#             Plugin Settings             #
#=========================================#
# The AutoMessager plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v${version}&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: automessager.plugininfo
default-can-see-plugin-information: false

# DO NOT CHANGE THIS!
config-version: 3
